apiVersion: v1
kind: ConfigMap
data:
  list.txt: |-
    passbolt.mtarget.co
    vault.mtarget.co
    bastillion.mtarget.co
metadata:
  name: gocheck-ssl-conf
  namespace: default

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gocheck-ssl
  labels:
    name: gocheck-ssl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: gocheck-ssl
          labels:
            name: gocheck-ssl
        spec:
          containers:
            - name: gocheck-ssl
              image: ghcr.io/mrofisr/gocheck:latest
              command:
                [
                  "/bin/gocheck",
                  "-L=/data/gocheck/list.txt",
                  "-webhook=https://discord.com/api/webhooks/906796914463354901/KQVg21rJKiQo7psJb-6BxJHc6PopObKoTYi7PnhKm9lBlsHe_GsmS3h-Q-gU4JIGyHlF",
                ]
              volumeMounts:
                - name: domain-list
                  mountPath: /data/gocheck
          volumes:
            - name: domain-list
              configMap:
                name: gocheck-ssl-conf
          restartPolicy: OnFailure
