apiVersion: v1
kind: ConfigMap
metadata:
  name: gocheck-ssl-config
data:
  list.txt: |
    mrofisr.dev
    google.com
    youtube.com
    mtarget.co
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gocheck-ssl
  labels:
    name: gocheck-ssl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: gocheck-ssl
          labels:
            name: gocheck-ssl
        spec:
          containers:
          - name: gocheck-ssl
            image: ghcr.io/mrofisr/gocheck:latest
            command:
              - /bin/gocheck
              - -L list.txt
              - -webhook https://discord.com/api/webhooks/887507194671689800/-rellZ-fxGBiHQ01ZF9ez98FKUuMxypGi1Gyq6bBT7c9vCGmKL7zaCYhkVwcEhC9PnDg
          restartPolicy: OnFailure
