apiVersion: v1
kind: ConfigMap
data:
  list.txt: |-
    mrofisr.dev
    google.com
    youtube.com
metadata:
  name: gocheck-ssl-conf
  namespace: default

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gocheck-ssl
  labels:
    name: gocheck-ssl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: gocheck-ssl
          labels:
            name: gocheck-ssl
        spec:
          containers:
            - name: gocheck-ssl
              image: ghcr.io/mrofisr/gocheck:latest
              command:
                [
                  "/bin/gocheck",
                  "-L=/data/gocheck/list.txt",
                  "-webhook=https://discord.com/api/webhooks/887507194671689800/-rellZ-fxGBiHQ01ZF9ez98FKUuMxypGi1Gyq6bBT7c9vCGmKL7zaCYhkVwcEhC9PnDg",
                ]
              volumeMounts:
                - name: domain-list
                  mountPath: /data/gocheck
          volumes:
            - name: domain-list
              configMap:
                name: gocheck-ssl-conf
          restartPolicy: OnFailure