apiVersion: batch/v1
kind: CronJob
metadata:
  name: gocheck-ssl
  labels:
    name: gocheck-ssl
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: gocheck-ssl
          labels:
            name: gocheck-ssl
        spec:
          containers:
            - name: gocheck-ssl
              image: ghcr.io/mrofisr/gocheck:latest
              command:
                [
                  "/bin/gocheck",
                  "-d=mrofisr.dev",
                  "-webhook=https://discord.com/api/webhooks/887507194671689800/-rellZ-fxGBiHQ01ZF9ez98FKUuMxypGi1Gyq6bBT7c9vCGmKL7zaCYhkVwcEhC9PnDg",
                ]
          restartPolicy: OnFailure